import { SimulatorConfig } from './types';

export const simulatorConfig: SimulatorConfig = {
  projectTypes: [
    {
      id: 'vitrine',
      name: 'Site vitrine',
      description: 'Présence web simple',
      basePrice: 900,
    },
    {
      id: 'institutionnel',
      name: 'Site institutionnel',
      description: 'Arborescence multi-pages',
      basePrice: 1200,
      impact: 'navigation-complexe',
    },
    {
      id: 'ecommerce',
      name: 'E-commerce',
      description: 'Catalogue, panier, paiements',
      basePrice: 2000,
      impact: 'modules-ecommerce',
    },
    {
      id: 'webapp',
      name: 'Web App / SaaS',
      description: 'Application dynamique avec comptes',
      basePrice: 2500,
      impact: 'auth-admin',
    },
    {
      id: 'refonte',
      name: 'Refonte',
      description: 'Refonte graphique ou technique',
      basePrice: 0, // -25% appliqué au total
      impact: 'migration',
    },
    {
      id: 'audit',
      name: 'Audit / Conseil',
      description: 'UX, performance, SEO',
      basePrice: 600,
      impact: 'rapports',
    },
    {
      id: 'design-system',
      name: 'Design System / UI Kit',
      description: 'Système de design complet',
      basePrice: 1000,
      impact: 'design-dev-team',
    },
    {
      id: 'prototype',
      name: 'Prototype / MVP',
      description: 'Version testable',
      basePrice: 800,
      impact: 'demo',
    },
    {
      id: 'landing',
      name: 'Landing Page',
      description: 'Page unique optimisée',
      basePrice: 500,
      impact: 'conversion',
    },
    {
      id: 'intranet',
      name: 'Intranet / Portail interne',
      description: 'Portail sécurisé interne',
      basePrice: 1800,
      impact: 'auth-securite',
    },
  ],

  designOptions: [
    // Direction artistique
    {
      id: 'design-custom',
      category: 'Direction artistique',
      name: 'Design sur mesure',
      description: 'Charte graphique complète',
      price: 500,
    },
    {
      id: 'design-refonte',
      category: 'Direction artistique',
      name: 'Refonte design',
      description: 'Adaptation design existant',
      price: 300,
    },
    {
      id: 'design-template',
      category: 'Direction artistique',
      name: 'Template personnalisé',
      description: 'Basé sur template modifié',
      price: 0,
    },

    // UX Design
    {
      id: 'ux-wireframes',
      category: 'UX Design',
      name: 'Wireframes',
      description: 'Schémas basse fidélité',
      price: 200,
    },
    {
      id: 'ux-prototype',
      category: 'UX Design',
      name: 'Prototypage interactif',
      description: 'Prototype Figma',
      price: 300,
      dependencies: ['ux-wireframes'],
    },
    {
      id: 'ux-tests',
      category: 'UX Design',
      name: 'Tests utilisateurs',
      description: 'Scénarios, itérations',
      price: 400,
      dependencies: ['ux-prototype'],
    },
    {
      id: 'ux-audit',
      category: 'UX Design',
      name: 'Audit UX',
      description: "Rapport d'analyse",
      price: 250,
    },

    // UI Design
    {
      id: 'ui-design-system',
      category: 'UI Design',
      name: 'Design system',
      description: 'Tokens, variables, composants',
      price: 800,
    },
    {
      id: 'ui-animations',
      category: 'UI Design',
      name: 'Animations',
      description: 'Transitions, Framer Motion',
      price: 250,
    },
    {
      id: 'ui-dark-mode',
      category: 'UI Design',
      name: 'Mode clair/sombre',
      description: 'Thème dynamique',
      price: 100,
    },
    {
      id: 'ui-accessibility',
      category: 'UI Design',
      name: 'Accessibilité',
      description: 'Respect WCAG',
      price: 200,
    },
  ],

  sectionOptions: [
    {
      id: 'header',
      name: 'Header',
      basicPrice: 80,
      advancedPrice: 120,
      premiumPrice: 200,
      descriptions: {
        basic: 'Header simple',
        advanced: 'Navigation multi-niveau',
        premium: 'Mega-menu sticky',
      },
    },
    {
      id: 'hero',
      name: 'Hero',
      basicPrice: 100,
      advancedPrice: 150,
      premiumPrice: 250,
      descriptions: {
        basic: 'Hero simple',
        advanced: 'Avec vidéo / 3D',
        premium: 'Animations avancées',
      },
    },
    {
      id: 'footer',
      name: 'Footer',
      basicPrice: 50,
      advancedPrice: 100,
      premiumPrice: 200,
      descriptions: {
        basic: 'Footer simple',
        advanced: 'Avec newsletter',
        premium: 'Multi-colonnes dynamiques',
      },
    },
    {
      id: 'services',
      name: 'Services',
      basicPrice: 100,
      advancedPrice: 150,
      premiumPrice: 250,
      descriptions: {
        basic: 'Liste simple',
        advanced: 'Cartes dynamiques',
        premium: 'Animation, filtres',
      },
    },
    {
      id: 'about',
      name: 'À propos',
      basicPrice: 60,
      advancedPrice: 100,
      premiumPrice: 180,
      descriptions: {
        basic: 'Présentation simple',
        advanced: 'Timeline, équipe',
        premium: 'Storytelling',
      },
    },
    {
      id: 'portfolio',
      name: 'Portfolio',
      basicPrice: 150,
      advancedPrice: 200,
      premiumPrice: 300,
      descriptions: {
        basic: 'Galerie simple',
        advanced: 'Filtrable',
        premium: 'Carrousel avancé',
      },
    },
    {
      id: 'blog',
      name: 'Blog',
      basicPrice: 200,
      advancedPrice: 250,
      premiumPrice: 350,
      descriptions: {
        basic: 'Articles simples',
        advanced: 'Avec pagination',
        premium: 'CMS dynamique',
      },
    },
    {
      id: 'contact',
      name: 'Contact',
      basicPrice: 60,
      advancedPrice: 100,
      premiumPrice: 150,
      descriptions: {
        basic: 'Formulaire simple',
        advanced: 'Formulaire complet',
        premium: 'Validation, reCAPTCHA',
      },
    },
    {
      id: 'faq',
      name: 'FAQ',
      basicPrice: 80,
      advancedPrice: 120,
      premiumPrice: 180,
      descriptions: {
        basic: 'Liste Q&R',
        advanced: 'Accordéon',
        premium: 'Recherche indexée',
      },
    },
    {
      id: 'testimonials',
      name: 'Témoignages',
      basicPrice: 80,
      advancedPrice: 120,
      premiumPrice: 160,
      descriptions: {
        basic: 'Liste simple',
        advanced: 'Slider',
        premium: 'CMS dynamique',
      },
    },
    {
      id: 'legal',
      name: 'Mentions légales',
      basicPrice: 50,
      advancedPrice: 80,
      premiumPrice: 120,
      descriptions: {
        basic: 'Page statique',
        advanced: 'Génération auto',
        premium: 'Multi-langues',
      },
    },
    {
      id: 'careers',
      name: 'Carrières',
      basicPrice: 100,
      advancedPrice: 180,
      premiumPrice: 300,
      descriptions: {
        basic: 'Offres simples',
        advanced: 'Formulaire RH',
        premium: 'Intégration Notion/API',
      },
    },
  ],

  technicalFeatures: [
    // Architecture
    {
      id: 'arch-static',
      category: 'Architecture',
      name: 'Statique',
      description: 'SSG / HTML',
      price: 0,
    },
    {
      id: 'arch-dynamic',
      category: 'Architecture',
      name: 'Dynamique',
      description: 'SSR / CMS',
      price: 300,
    },
    {
      id: 'arch-headless',
      category: 'Architecture',
      name: 'Headless CMS',
      description: 'Strapi / Sanity',
      price: 250,
      conditions: 'dynamique',
      requiredFeatures: ['arch-dynamic'],
    },

    // Auth
    {
      id: 'auth-basic',
      category: 'Authentification',
      name: 'Basique',
      description: 'Login / Register',
      price: 150,
      conditions: 'dynamique',
      requiredFeatures: ['arch-dynamic'],
    },
    {
      id: 'auth-advanced',
      category: 'Authentification',
      name: 'Avancée',
      description: 'OAuth / JWT / RBAC',
      price: 300,
      conditions: 'dynamique',
      requiredFeatures: ['arch-dynamic'],
    },

    // Back-office
    {
      id: 'backoffice-crud',
      category: 'Back-office',
      name: 'CRUD',
      description: 'Gestion contenu',
      price: 300,
      conditions: 'dynamique',
      requiredFeatures: ['arch-dynamic'],
    },
    {
      id: 'backoffice-dashboard',
      category: 'Back-office',
      name: 'Dashboard analytique',
      description: 'Graphiques / stats',
      price: 200,
      conditions: 'admin',
      requiredFeatures: ['backoffice-crud'],
    },

    // E-commerce
    {
      id: 'ecom-catalog',
      category: 'E-commerce',
      name: 'Catalogue',
      description: 'Produits / catégories',
      price: 300,
      conditions: 'dynamique',
      requiredFeatures: ['arch-dynamic'],
    },
    {
      id: 'ecom-checkout',
      category: 'E-commerce',
      name: 'Checkout',
      description: 'Stripe / PayPal',
      price: 250,
      conditions: 'catalogue',
      requiredFeatures: ['ecom-catalog'],
    },
    {
      id: 'ecom-orders',
      category: 'E-commerce',
      name: 'Commandes',
      description: 'Statuts, historique',
      price: 200,
      conditions: 'back-office',
      requiredFeatures: ['backoffice-crud'],
    },
    {
      id: 'ecom-emails',
      category: 'E-commerce',
      name: 'Emails transactionnels',
      description: 'Factures, reçus',
      price: 150,
    },

    // Documents
    {
      id: 'doc-pdf',
      category: 'Documents',
      name: 'Génération PDF',
      description: 'Devis, factures',
      price: 200,
      conditions: 'dynamique',
      requiredFeatures: ['arch-dynamic'],
    },
    {
      id: 'doc-signature',
      category: 'Documents',
      name: 'Signature électronique',
      description: 'DocuSign',
      price: 150,
      requiredFeatures: ['doc-pdf'],
    },

    // API / intégrations
    {
      id: 'api-external',
      category: 'API / intégrations',
      name: 'API externe',
      description: 'Services tiers',
      price: 150,
      conditions: 'dynamique',
      requiredFeatures: ['arch-dynamic'],
    },
    {
      id: 'api-webhooks',
      category: 'API / intégrations',
      name: 'Webhooks',
      description: 'Zapier, Make',
      price: 100,
      conditions: 'dynamique',
      requiredFeatures: ['arch-dynamic'],
    },

    // Stockage
    {
      id: 'storage-upload',
      category: 'Stockage',
      name: 'Upload fichiers',
      description: 'Cloud / S3',
      price: 100,
      conditions: 'dynamique',
      requiredFeatures: ['arch-dynamic'],
    },
    {
      id: 'storage-images',
      category: 'Stockage',
      name: 'Optimisation images',
      description: 'Responsive / lazy load',
      price: 80,
    },
    {
      id: 'storage-video',
      category: 'Stockage',
      name: 'Vidéothèque',
      description: 'Gestion vidéo',
      price: 120,
    },

    // Notifications
    {
      id: 'notif-email',
      category: 'Notifications',
      name: 'Email',
      description: 'SMTP / EmailJS',
      price: 80,
    },
    {
      id: 'notif-push',
      category: 'Notifications',
      name: 'Push',
      description: 'Firebase / WS',
      price: 150,
      conditions: 'dynamique',
      requiredFeatures: ['arch-dynamic'],
    },

    // Recherche
    {
      id: 'search-basic',
      category: 'Recherche',
      name: 'Basique',
      description: 'Filtrage / mots-clés',
      price: 120,
      conditions: 'dynamique',
      requiredFeatures: ['arch-dynamic'],
    },
    {
      id: 'search-advanced',
      category: 'Recherche',
      name: 'Avancée',
      description: 'Algolia / Meilisearch',
      price: 300,
      conditions: 'dynamique',
      requiredFeatures: ['arch-dynamic'],
    },
  ],

  maintenanceOptions: [
    {
      id: 'maint-basic',
      name: 'Basique',
      description: 'Corrections',
      setupPrice: 50,
      monthlyPrice: 50,
    },
    {
      id: 'maint-premium',
      name: 'Premium',
      description: 'MàJ + support',
      setupPrice: 150,
      monthlyPrice: 100,
    },
    {
      id: 'maint-pro',
      name: 'Pro',
      description: 'SLA, monitoring',
      setupPrice: 300,
      monthlyPrice: 150,
    },
    {
      id: 'security-ssl',
      name: 'SSL, headers',
      description: 'Configuration sécurisée',
      setupPrice: 80,
      monthlyPrice: 0,
    },
    {
      id: 'security-audit',
      name: 'Audit',
      description: 'Tests OWASP',
      setupPrice: 200,
      monthlyPrice: 0,
    },
    {
      id: 'hosting-vercel',
      name: 'Vercel/Netlify',
      description: 'Setup + DNS',
      setupPrice: 50,
      monthlyPrice: 25,
    },
    {
      id: 'hosting-vps',
      name: 'VPS',
      description: 'Déploiement dédié',
      setupPrice: 200,
      monthlyPrice: 60,
    },
    {
      id: 'backup-auto',
      name: 'Sauvegarde auto',
      description: 'Base + fichiers',
      setupPrice: 100,
      monthlyPrice: 30,
    },
    {
      id: 'monitoring',
      name: 'Monitoring',
      description: 'Uptime, logs',
      setupPrice: 80,
      monthlyPrice: 15,
    },
  ],

  performanceOptions: [
    {
      id: 'seo-basic',
      name: 'SEO basique',
      description: 'Métas, sitemap',
      price: 100,
    },
    {
      id: 'seo-advanced',
      name: 'SEO avancé',
      description: 'Schema.org, OG, Snippets',
      price: 200,
    },
    {
      id: 'seo-technical',
      name: 'SEO technique',
      description: 'Core Web Vitals',
      price: 250,
    },
    {
      id: 'perf-lighthouse',
      name: 'Performance',
      description: 'Lighthouse >90',
      price: 200,
    },
    {
      id: 'analytics',
      name: 'Analytics',
      description: 'GA / Plausible',
      price: 100,
    },
    {
      id: 'tracking',
      name: 'Tracking',
      description: 'Pixels, events',
      price: 100,
    },
    {
      id: 'ab-testing',
      name: 'A/B Testing',
      description: 'Split tests',
      price: 150,
    },
  ],

  contentOptions: [
    // Rédaction
    {
      id: 'content-seo',
      category: 'Rédaction',
      name: 'Textes SEO',
      description: 'par page',
      price: 100,
      unit: 'page',
    },
    {
      id: 'content-copywriting',
      category: 'Rédaction',
      name: 'Copywriting',
      description: 'par page',
      price: 200,
      unit: 'page',
    },
    {
      id: 'content-translation',
      category: 'Rédaction',
      name: 'Traduction',
      description: 'par langue',
      price: 100,
      unit: 'langue',
    },

    // Visuel
    {
      id: 'visual-illustrations',
      category: 'Visuel',
      name: 'Illustrations',
      description: 'Illustrations sur mesure',
      price: 150,
      unit: 'illustration',
    },
    {
      id: 'visual-icons',
      category: 'Visuel',
      name: 'Iconographie',
      description: 'Pack d\'icônes',
      price: 100,
      unit: 'pack',
    },
    {
      id: 'visual-photos',
      category: 'Visuel',
      name: 'Photos / retouches',
      description: 'Photos professionnelles',
      price: 150,
      unit: 'série',
    },

    // Marketing
    {
      id: 'marketing-launch',
      category: 'Marketing',
      name: 'Lancement',
      description: 'Stratégie de lancement',
      price: 200,
      unit: 'forfait',
    },
    {
      id: 'marketing-newsletter',
      category: 'Marketing',
      name: 'Newsletter',
      description: 'Intégration newsletter',
      price: 120,
      unit: 'forfait',
    },
    {
      id: 'marketing-social',
      category: 'Marketing',
      name: 'Stratégie SM',
      description: 'Social Media',
      price: 250,
      unit: 'forfait',
    },

    // Formation
    {
      id: 'training-client',
      category: 'Formation',
      name: 'Client',
      description: 'Formation utilisateur',
      price: 150,
      unit: 'session',
    },
    {
      id: 'training-doc',
      category: 'Formation',
      name: 'Documentation',
      description: 'Documentation technique',
      price: 100,
      unit: 'forfait',
    },
  ],
};
